amcl:
  ros__parameters:
    use_sim_time: false
    scan_topic: scan
    min_particles: 100
    max_particles: 5000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    tf_broadcast: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    update_min_d: 0.25
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 0.2
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/mario/farm_bot/src/farm_bot_vision/config/map.yaml"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    goal_blackboard_id: "goal"
    cancel_blackboard_id: "cancel"
    failure_blackboard_id: "failure"
    path_blackboard_id: "path"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath.plugin: "nav2_controller::FollowPathController"
    min_theta_velocity: 0.4
    max_theta_velocity: 1.0

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased.plugin: "nav2_navfn_planner/NavfnPlanner"

behavior_server:
  ros__parameters:
    use_sim_time: false
    behavior_plugins: ["spin", "backup", "wait"]
    spin.plugin: "nav2_behaviors/Spin"
    backup.plugin: "nav2_behaviors/BackUp"
    wait.plugin: "nav2_behaviors/Wait"

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: false
